# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_RxCocoa' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
    pod 'RxSwift' 
    pod 'RxCocoa' 
  # Pods for RxSwift_RxCocoa

  target 'RxSwift_RxCocoaTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking' 
    pod 'RxTest' 
  end

  target 'RxSwift_RxCocoaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
