# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Settings' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire' ,'~> 4.8.2'
  pod 'AlamofireImage', '~> 3.5' 
  pod 'QorumLogs'
  pod 'IQKeyboardManagerSwift'
  pod 'PinLayout'
  pod 'CustomUISwitch'
  # Pods for Settings

end
