# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'FirebaseMessaging'
  pod 'RxSwift'
  pod 'ReactiveCocoa', '~> 10.1'
  pod 'RxCocoa' 
  pod 'RxTheme'
  pod 'IQKeyboardManagerSwift' 
  pod 'NotificationBannerSwift', '1.6.3'
  pod 'MarqueeLabel/Swift', '3.1.6'
  # Pods for Chat
 post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
    end
  end
end
