# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Localization' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'LanguageManager-iOS'
  pod 'Firebase/Core'
  pod 'FirebaseMessaging'
  # Pods for Localization

end
