# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProgressAnimation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'GradientLoadingBar', '~> 2.0'
   pod 'ButtonProgressBar-iOS'
  # Pods for ProgressAnimation

end
